class MaterialCriticality:
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class SupplierStatus:
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    BLACKLISTED = "BLACKLISTED"


class MovementType:
    RECEIPT = "RECEIPT"
    CONSUMPTION = "CONSUMPTION"
    TRANSFER = "TRANSFER"
    ADJUSTMENT = "ADJUSTMENT"
    DAMAGE = "DAMAGE"
    RESERVATION = "RESERVATION"
    RELEASE = "RELEASE"
    RETURN = "RETURN"


class POStatus:
    DRAFT = "DRAFT"
    CONFIRMED = "CONFIRMED"
    IN_PRODUCTION = "IN_PRODUCTION"
    SHIPPED = "SHIPPED"
    DELIVERED = "DELIVERED"
    DELAYED = "DELAYED"
    CANCELLED = "CANCELLED"
    PARTIALLY_RECEIVED = "PARTIALLY_RECEIVED"


class ShipmentStatus:
    LABEL_CREATED = "LABEL_CREATED"
    PICKUP_PENDING = "PICKUP_PENDING"
    PICKED_UP = "PICKED_UP"
    IN_TRANSIT = "IN_TRANSIT"
    OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY"
    DELIVERED = "DELIVERED"
    CANCELLED = "CANCELLED"


class ProductionStatus:
    PLANNED = "PLANNED"
    RELEASED = "RELEASED"
    IN_PROGRESS = "IN_PROGRESS"
    ON_HOLD = "ON_HOLD"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class RiskLevel:
    NONE = "NONE"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class IncidentStatus:
    OPEN = "OPEN"
    ANALYZING = "ANALYZING"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    APPROVED = "APPROVED"
    EXECUTING = "EXECUTING"
    VERIFYING = "VERIFYING"
    RESOLVED = "RESOLVED"
    REJECTED = "REJECTED"
    REPLANNING = "REPLANNING"
    CLOSED = "CLOSED"


class PlanType:
    SINGLE_SOURCE = "SINGLE_SOURCE"
    SPLIT_SOURCE = "SPLIT_SOURCE"
    PARTIAL_SHIPMENT = "PARTIAL_SHIPMENT"
    STOCK_ADJUSTMENT = "STOCK_ADJUSTMENT"
    RESCHEDULE = "RESCHEDULE"
    COMBINED = "COMBINED"


class PlanStatus:
    PROPOSED = "PROPOSED"
    VALIDATED = "VALIDATED"
    INVALID = "INVALID"
    SIMULATED = "SIMULATED"
    RECOMMENDED = "RECOMMENDED"
    APPROVED = "APPROVED"
    EXECUTING = "EXECUTING"
    EXECUTED = "EXECUTED"
    FAILED = "FAILED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class ApprovalStatus:
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    MODIFICATION_REQUESTED = "MODIFICATION_REQUESTED"
    EXPIRED = "EXPIRED"


class WorkflowType:
    SUPPLY_DISRUPTION = "SUPPLY_DISRUPTION"
    STALE_INVENTORY = "STALE_INVENTORY"
    CLAIM_MISMATCH = "CLAIM_MISMATCH"
    QUALITY_CONSTRAINT = "QUALITY_CONSTRAINT"
    BUDGET_APPROVAL = "BUDGET_APPROVAL"
    PRODUCTION_RISK = "PRODUCTION_RISK"


class EventType:
    INCIDENT_CREATED = "INCIDENT_CREATED"
    RISK_CALCULATION = "RISK_CALCULATION"
    SUPPLIER_EVALUATION = "SUPPLIER_EVALUATION"
    RECOMMENDATION = "RECOMMENDATION"
    PLAN_VALIDATION = "PLAN_VALIDATION"
    SIMULATION = "SIMULATION"
    APPROVAL_REQUESTED = "APPROVAL_REQUESTED"
    APPROVAL_DECISION = "APPROVAL_DECISION"
    EXECUTION = "EXECUTION"
    VERIFICATION = "VERIFICATION"
    REPLAN_TRIGGERED = "REPLAN_TRIGGERED"


class AdjustmentApprovalStatus:
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
