"""phase1 core operational tables

Revision ID: c2c7b0b76a5c
Revises: 
Create Date: 2026-08-22 22:34:26.652004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c2c7b0b76a5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('material_id', sa.String(length=32), nullable=False),
    sa.Column('material_code', sa.String(length=64), nullable=False),
    sa.Column('material_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=16), nullable=False),
    sa.Column('criticality_level', sa.String(length=16), nullable=False),
    sa.Column('required_quality_level', sa.String(length=16), nullable=False),
    sa.Column('required_certification', sa.String(length=128), nullable=True),
    sa.Column('safety_stock', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reorder_point', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('lead_time_target_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("criticality_level IN ('LOW','MEDIUM','HIGH','CRITICAL')", name=op.f('ck_materials_valid_criticality')),
    sa.PrimaryKeyConstraint('material_id', name=op.f('pk_materials')),
    sa.UniqueConstraint('material_code', name=op.f('uq_materials_material_code'))
    )
    op.create_table('production_orders',
    sa.Column('production_order_id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('planned_quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('completed_quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('remaining_quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('production_rate_per_hour', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('line_id', sa.String(length=32), nullable=True),
    sa.Column('customer_order_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('production_order_id', name=op.f('pk_production_orders'))
    )
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.String(length=32), nullable=False),
    sa.Column('supplier_code', sa.String(length=64), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('contact_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('overall_reliability_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('on_time_delivery_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('average_lead_time_days', sa.Integer(), nullable=False),
    sa.Column('payment_terms', sa.String(length=64), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('supplier_id', name=op.f('pk_suppliers')),
    sa.UniqueConstraint('supplier_code', name=op.f('uq_suppliers_supplier_code'))
    )
    op.create_table('inventory_movements',
    sa.Column('movement_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.String(length=32), nullable=False),
    sa.Column('warehouse_id', sa.String(length=32), nullable=False),
    sa.Column('movement_type', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reference_type', sa.String(length=32), nullable=True),
    sa.Column('reference_id', sa.String(length=64), nullable=True),
    sa.Column('movement_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.material_id'], name=op.f('fk_inventory_movements_material_id_materials'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movement_id', name=op.f('pk_inventory_movements'))
    )
    op.create_table('inventory_pricing_adjustments',
    sa.Column('adjustment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.String(length=32), nullable=False),
    sa.Column('supplier_id', sa.String(length=32), nullable=True),
    sa.Column('batch_id', sa.String(length=64), nullable=True),
    sa.Column('original_unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('damage_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('quality_degradation', sa.String(length=32), nullable=False),
    sa.Column('adjusted_unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('adjustment_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('calculation_method', sa.String(length=64), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('approval_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.material_id'], name=op.f('fk_inventory_pricing_adjustments_material_id_materials'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], name=op.f('fk_inventory_pricing_adjustments_supplier_id_suppliers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('adjustment_id', name=op.f('pk_inventory_pricing_adjustments'))
    )
    op.create_table('inventory_snapshots',
    sa.Column('snapshot_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.String(length=32), nullable=False),
    sa.Column('warehouse_id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('erp_quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('physical_quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('usable_quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reserved_quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('damaged_quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('blocked_quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('in_transit_quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('available_quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.material_id'], name=op.f('fk_inventory_snapshots_material_id_materials'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('pk_inventory_snapshots'))
    )
    op.create_table('material_specifications',
    sa.Column('specification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.String(length=32), nullable=False),
    sa.Column('material_grade', sa.String(length=64), nullable=True),
    sa.Column('material_type', sa.String(length=64), nullable=True),
    sa.Column('dimensions', sa.String(length=128), nullable=True),
    sa.Column('dimension_tolerance', sa.String(length=64), nullable=True),
    sa.Column('weight', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('weight_tolerance', sa.String(length=64), nullable=True),
    sa.Column('density', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('surface_finish', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('chemical_composition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mechanical_properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('aql_level', sa.String(length=16), nullable=True),
    sa.Column('inspection_standard', sa.String(length=64), nullable=True),
    sa.Column('required_certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('special_requirements', sa.String(length=512), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.material_id'], name=op.f('fk_material_specifications_material_id_materials'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('specification_id', name=op.f('pk_material_specifications'))
    )
    op.create_table('production_consumption',
    sa.Column('consumption_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('production_order_id', sa.String(length=32), nullable=False),
    sa.Column('material_id', sa.String(length=32), nullable=False),
    sa.Column('quantity_consumed', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('consumption_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_quantity', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('actual_quantity', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.material_id'], name=op.f('fk_production_consumption_material_id_materials'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.production_order_id'], name=op.f('fk_production_consumption_production_order_id_production_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('consumption_id', name=op.f('pk_production_consumption'))
    )
    op.create_table('purchase_orders',
    sa.Column('po_id', sa.String(length=32), nullable=False),
    sa.Column('po_number', sa.String(length=64), nullable=False),
    sa.Column('supplier_id', sa.String(length=32), nullable=False),
    sa.Column('material_id', sa.String(length=32), nullable=False),
    sa.Column('ordered_quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('received_quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('remaining_quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_delivery_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('production_order_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.material_id'], name=op.f('fk_purchase_orders_material_id_materials'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.production_order_id'], name=op.f('fk_purchase_orders_production_order_id_production_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], name=op.f('fk_purchase_orders_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('po_id', name=op.f('pk_purchase_orders')),
    sa.UniqueConstraint('po_number', name=op.f('uq_purchase_orders_po_number'))
    )
    op.create_table('risk_thresholds',
    sa.Column('threshold_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.String(length=32), nullable=True),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('warning_threshold', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('critical_threshold', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('comparison_operator', sa.String(length=8), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.material_id'], name=op.f('fk_risk_thresholds_material_id_materials'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('threshold_id', name=op.f('pk_risk_thresholds'))
    )
    op.create_table('supplier_materials',
    sa.Column('supplier_material_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.String(length=32), nullable=False),
    sa.Column('material_id', sa.String(length=32), nullable=False),
    sa.Column('available_quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reserved_quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('available_to_promise', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('minimum_order_quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('maximum_order_quantity', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('expedited_lead_time_days', sa.Integer(), nullable=True),
    sa.Column('quality_grade', sa.String(length=16), nullable=True),
    sa.Column('aql_level', sa.String(length=16), nullable=True),
    sa.Column('inspection_standard', sa.String(length=64), nullable=True),
    sa.Column('material_grade', sa.String(length=64), nullable=True),
    sa.Column('material_specification', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('measurement_tolerance', sa.String(length=64), nullable=True),
    sa.Column('certification_required', sa.String(length=128), nullable=True),
    sa.Column('certification_valid', sa.Boolean(), nullable=False),
    sa.Column('certification_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('batch_size', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('production_capacity', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.material_id'], name=op.f('fk_supplier_materials_material_id_materials'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], name=op.f('fk_supplier_materials_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('supplier_material_id', name=op.f('pk_supplier_materials'))
    )
    op.create_table('supplier_performance',
    sa.Column('performance_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.String(length=32), nullable=False),
    sa.Column('evaluation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('orders_completed', sa.Integer(), nullable=False),
    sa.Column('orders_on_time', sa.Integer(), nullable=False),
    sa.Column('orders_late', sa.Integer(), nullable=False),
    sa.Column('average_delay_days', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('quality_rejection_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('eta_change_count', sa.Integer(), nullable=False),
    sa.Column('claim_mismatch_count', sa.Integer(), nullable=False),
    sa.Column('tracking_discrepancy_count', sa.Integer(), nullable=False),
    sa.Column('average_response_time', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('reliability_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], name=op.f('fk_supplier_performance_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('performance_id', name=op.f('pk_supplier_performance'))
    )
    op.create_table('supplier_quotes',
    sa.Column('quote_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.String(length=32), nullable=False),
    sa.Column('material_id', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('certification_level', sa.String(length=64), nullable=True),
    sa.Column('certification_valid', sa.Boolean(), nullable=False),
    sa.Column('minimum_order_quantity', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('quote_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('availability', sa.String(length=32), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.material_id'], name=op.f('fk_supplier_quotes_material_id_materials'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], name=op.f('fk_supplier_quotes_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quote_id', name=op.f('pk_supplier_quotes'))
    )
    op.create_table('incidents',
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('incident_type', sa.String(length=64), nullable=False),
    sa.Column('material_id', sa.String(length=32), nullable=True),
    sa.Column('po_id', sa.String(length=32), nullable=True),
    sa.Column('supplier_id', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('workflow_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.material_id'], name=op.f('fk_incidents_material_id_materials'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.po_id'], name=op.f('fk_incidents_po_id_purchase_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], name=op.f('fk_incidents_supplier_id_suppliers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('incident_id', name=op.f('pk_incidents'))
    )
    op.create_table('material_spec_parameters',
    sa.Column('parameter_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('specification_id', sa.Integer(), nullable=False),
    sa.Column('parameter_name', sa.String(length=128), nullable=False),
    sa.Column('parameter_type', sa.String(length=32), nullable=False),
    sa.Column('target_value', sa.String(length=64), nullable=True),
    sa.Column('min_value', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('tolerance', sa.String(length=64), nullable=True),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['specification_id'], ['material_specifications.specification_id'], name=op.f('fk_material_spec_parameters_specification_id_material_specifications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parameter_id', name=op.f('pk_material_spec_parameters'))
    )
    op.create_table('shipments',
    sa.Column('shipment_id', sa.String(length=32), nullable=False),
    sa.Column('po_id', sa.String(length=32), nullable=False),
    sa.Column('tracking_number', sa.String(length=64), nullable=True),
    sa.Column('shipment_status', sa.String(length=32), nullable=False),
    sa.Column('label_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pickup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispatch_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_delivery', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_delivery', sa.DateTime(timezone=True), nullable=True),
    sa.Column('carrier', sa.String(length=64), nullable=True),
    sa.Column('last_tracking_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tracking_location', sa.String(length=128), nullable=True),
    sa.Column('tracking_source', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.po_id'], name=op.f('fk_shipments_po_id_purchase_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shipment_id', name=op.f('pk_shipments'))
    )
    op.create_table('supplier_communications',
    sa.Column('communication_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.String(length=32), nullable=False),
    sa.Column('po_id', sa.String(length=32), nullable=True),
    sa.Column('message_type', sa.String(length=32), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('claimed_status', sa.String(length=32), nullable=True),
    sa.Column('claimed_quantity', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('claimed_eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_dispatch_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.po_id'], name=op.f('fk_supplier_communications_po_id_purchase_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], name=op.f('fk_supplier_communications_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('communication_id', name=op.f('pk_supplier_communications'))
    )
    op.create_table('audit_events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=True),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], name=op.f('fk_audit_events_incident_id_incidents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_audit_events'))
    )
    op.create_table('recovery_plans',
    sa.Column('plan_id', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('plan_name', sa.String(length=255), nullable=False),
    sa.Column('plan_type', sa.String(length=32), nullable=False),
    sa.Column('plan_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estimated_delivery_days', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('production_impact_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('supplier_risk_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('robustness_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], name=op.f('fk_recovery_plans_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id', name=op.f('pk_recovery_plans'))
    )
    op.create_table('approval_requests',
    sa.Column('approval_id', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('plan_id', sa.String(length=32), nullable=True),
    sa.Column('requested_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('approval_threshold', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('production_impact', sa.String(length=255), nullable=True),
    sa.Column('risk_if_rejected', sa.String(length=255), nullable=True),
    sa.Column('alternatives_considered', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('decision_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_reason', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], name=op.f('fk_approval_requests_incident_id_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['recovery_plans.plan_id'], name=op.f('fk_approval_requests_plan_id_recovery_plans'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('approval_id', name=op.f('pk_approval_requests'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approval_requests')
    op.drop_table('recovery_plans')
    op.drop_table('audit_events')
    op.drop_table('supplier_communications')
    op.drop_table('shipments')
    op.drop_table('material_spec_parameters')
    op.drop_table('incidents')
    op.drop_table('supplier_quotes')
    op.drop_table('supplier_performance')
    op.drop_table('supplier_materials')
    op.drop_table('risk_thresholds')
    op.drop_table('purchase_orders')
    op.drop_table('production_consumption')
    op.drop_table('material_specifications')
    op.drop_table('inventory_snapshots')
    op.drop_table('inventory_pricing_adjustments')
    op.drop_table('inventory_movements')
    op.drop_table('suppliers')
    op.drop_table('production_orders')
    op.drop_table('materials')
    # ### end Alembic commands ###
